version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  todo-backend:
    build: ./backend
    image: todo101-todo-backend:latest
    ports:
      - "15000:15000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos
    depends_on:
      - mongo
  
  todo-frontend:
    build: ./frontend
    image: todo101-todo-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - todo-backend
